// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// OrderRepository is an autogenerated mock type for the OrderRepository type
type OrderRepository struct {
	mock.Mock
}

// InsertCart provides a mock function with given fields: ctx, userID
func (_m *OrderRepository) InsertCart(ctx context.Context, userID int) (int, error) {
	ret := _m.Called(ctx, userID)

	var r0 int
	if rf, ok := ret.Get(0).(func(context.Context, int) int); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertCartItems provides a mock function with given fields: ctx, cartID, productCode, Qty
func (_m *OrderRepository) InsertCartItems(ctx context.Context, cartID int, productCode string, Qty int) error {
	ret := _m.Called(ctx, cartID, productCode, Qty)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, string, int) error); ok {
		r0 = rf(ctx, cartID, productCode, Qty)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
